version: '3.5'

services:
  api:
    build: .
    image: yelp-like-api
    ports:
      - "8000:8000" 
    depends_on:
      - mongo-server
    environment:
      MONGO_DB: mongodb
      MONGO_USER: mongouser
      MONGO_PASSWORD: hunter2
      MONGO_HOST: mongo-server
      MONGO_PORT: 27017
    

  mongo-server:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MONGO_HOST: mongo-server
      MONGO_USER: ${MONGO_USERNAME}
      MONGO_PORT: 27017
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hunter
      MONGO_INITDB_DATABASE: mongodb

volumes:
  mongo-data:
    name: mongo-data
